version: '3.9'

services:
  poglin-bot-go:
    image: pogbot:ubuntu
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: poglin-bot-go
    environment:
      - DISCORD_API=$DISCORD_API
    restart: unless-stopped