version: '3.9'

services:
  poglin-bot-go:
    image: pogbot:alpine
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: poglin-bot-go
    volumes:
      - ./cookies.txt:/app/cookies.txt
    environment:
      - DISCORD_API=$DISCORD_DEV_API
    restart: unless-stopped