version: '3.9'

services:
  poglin-bot-go:
    image: ghcr.io/eliabir/poglin-bot-go:v0.0.1-alpine
    container_name: poglin-bot-go
    environment:
      - DISCORD_API=$DISCORD_API
    restart: unless-stopped