services:
  poglin-bot-go-ubuntu-testing:
    image: pogbot:ubuntu-testing
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: poglin-bot-go-testing
    volumes:
      - ./cookies.txt:/app/cookies.txt
    environment:
      - DISCORD_API=$DISCORD_DEV_API
    restart: unless-stopped
